### ISSUE TITLE
Missing jsdom dependency

### ISSUE THREAD

**Issue by danielcodes** [dceddia/getting-started-with-tdd-in-react#1]
Hi, just letting you know that `package.json` is missing the `jsdom` dependency

**Comment by climboid** [comment]
same here

**Comment by aaayumi** [comment]
Same here. I got the following error message.

 react-tdd-demo@1.0.0 test /Users/ayumisaito/getting-started-with-tdd-in-react mocha --require setup.js *.spec.js

/Users/ayumisaito/getting-started-with-tdd-in-react/setup.js:7
global.document = jsdom('');
                  ^

TypeError: jsdom is not a function
    at Object.<anonymous> (/Users/ayumisaito/getting-started-with-tdd-in-react/setup.js:7:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at /usr/local/lib/node_modules/mocha/bin/_mocha:366:3
    at Array.forEach (native)
    at Object.<anonymous> (/usr/local/lib/node_modules/mocha/bin/_mocha:365:10)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
